---
title: "EMA Modeling"
author: "Dani Cosme & Rich Lopez"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE)
```

# load packages
```{r}
library(tidyverse)
library(lmerTest)
```

# define palettes
```{r}
pal_process = wesanderson::wes_palette("Zissou1", 6, "continuous")
```

# source data
```{r}
source("load_data.R")
```

# standardize brain data
```{r}
# standardize and winsorize
betas_std = betas %>%
  group_by(roi, session) %>%
  mutate(meanPE_std = scale(meanPE, center = TRUE, scale = TRUE),
         meanPE_std = ifelse(meanPE_std > 3, 3,
                      ifelse(meanPE_std < -3, -3, meanPE_std))) %>%
  ungroup()

dots_std = dots %>%
  group_by(map, test, mask, session) %>%
  mutate(dotProduct_std = scale(dotProduct, center = TRUE, scale = TRUE),
         dotProduct_std = ifelse(dotProduct_std > 3, 3,
                          ifelse(dotProduct_std < -3, -3, dotProduct_std))) %>%
  ungroup()

# join data frames
dataset = full_join(betas_std, dots_std, by = c("subjectID", "con", "process", "condition", "control", "session")) %>%
  mutate(subjectID = as.character(subjectID)) %>%
  ungroup() %>%
  mutate(subjectID = as.factor(subjectID),
         condition = as.factor(condition),
         control = as.factor(control),
         roi = as.factor(roi),
         process = as.factor(process),
         test = as.factor(test))
```

# tidy data
```{r}
ema_tidy = ema %>%
  select(subjectID, desire_pres0.prop, desire_str.m, goal_conf.m, resist.m, enact_prop, amount_Recoded.m, hunger.m) %>%
  unique()

model_data = dataset %>%
  filter(((!grepl("neuralsig", map) & test == "association" & mask == "masked") | (grepl("neuralsig", map) & mask == "unmasked")) & 
           session == "all" & control == "nature" & condition == "snack") %>%
  unique() %>%
  group_by(process, subjectID) %>%
  mutate(meanProcessPEstd = mean(meanPE_std, na.rm = TRUE),
         processPE = paste0(process, "_ROI"),
         processPEV = paste0(process, "_PEV")) %>%
  ungroup() %>%
  select(-c(xyz, meanPE, meanPE_std, sdPE, dotProduct, map, process)) %>%
  spread(processPEV, dotProduct_std) %>%
  spread(processPE, meanProcessPEstd) %>%
  group_by(subjectID) %>%
  fill(everything(), .direction = "down") %>%
  fill(everything(), .direction = "up") %>%
  select(-c(roi, craving_ROI, craving_regulation_ROI, test, mask)) %>%
  unique() %>%
  mutate(balance_ROI = cognitive_control_ROI - reward_ROI) %>%
  right_join(., ema_tidy, by = "subjectID") %>%
  na.omit()
```

# visualize {.tabset}
## ROIs
```{r, fig.width=8, fig.height=5}
model_data %>%
  select(subjectID, contains("ROI"), desire_pres0.prop, desire_str.m, goal_conf.m, resist.m, enact_prop, amount_Recoded.m) %>%
  unique() %>%
  gather(neuro_var, neuro_val, contains("ROI")) %>%
  mutate(neuro_var = factor(neuro_var, levels = c("balance_ROI", "cognitive_control_ROI",
                                                  "reward_ROI", "value_ROI"))) %>%
  gather(ema_var, ema_val, contains("m"), contains("prop")) %>%
  group_by(ema_var) %>%
  do({
    plot = ggplot(., aes(neuro_val, ema_val, color = neuro_var)) +
      geom_point(alpha = .5) +
      geom_smooth(method = "lm", alpha = .1, fullrange = TRUE) +
      scale_color_manual(name = "", values = pal_process) +
      labs(x = "\n mean parameter estimate", y = paste0(.$ema_var[[1]], "\n")) +
      theme_minimal(base_size = 14)
    
    print(plot)
    data.frame()
  })
```

## MAMs
```{r, fig.width=8, fig.height=5}
model_data %>%
  select(subjectID, contains("PEV"), desire_pres0.prop, desire_str.m, goal_conf.m, resist.m, enact_prop, amount_Recoded.m) %>%
  unique() %>%
  gather(neuro_var, neuro_val, contains("PEV")) %>%
  mutate(neuro_var = factor(neuro_var, levels = c("cognitive_control_PEV", "reward_PEV", "value_PEV",
                                                  "craving_PEV", "craving_regulation_PEV"))) %>%
  gather(ema_var, ema_val, contains("m"), contains("prop")) %>%
  group_by(ema_var) %>%
  do({
    plot = ggplot(., aes(neuro_val, ema_val, color = neuro_var)) +
      geom_point(alpha = .5) +
      geom_smooth(method = "lm", alpha = .1, fullrange = TRUE) +
      scale_color_manual(name = "", values = pal_process[2:6]) +
      labs(x = "\n mean parameter estimate", y = paste0(.$ema_var[[1]], "\n")) +
      theme_minimal(base_size = 14)
    
    print(plot)
    data.frame()
  })

```


# run regression models
## specify model variables
```{r}
options(na.action = "na.fail")
data_ctrl = caret::trainControl(method = "repeatedcv", number = 5, repeats = 5)
```

## desire presence proportion {.tabset}
### ROI models
```{r}
desire_prop_roi_full = lm(desire_pres0.prop ~ value_ROI + reward_ROI + cognitive_control_ROI, data = model_data)
(desire_prop_roi_mods = MuMIn::dredge(desire_prop_roi_full))
```

```{r}
MuMIn::get.models(desire_prop_roi_mods, subset = TRUE) %>%
  tibble() %>%
  rename("model" = ".") %>%
  mutate(tidied = purrr::map(model, broom::tidy),
         model_num = row_number()) %>%
  select(model_num, tidied) %>%
  unnest()

best_desire_prop_roi = caret::train(desire_pres0.prop ~ reward_ROI,
                     data = model_data,
                     trControl = data_ctrl,
                     method = "lm",
                     na.action = na.omit)
```

### MAM models
```{r}
desire_prop_mam_full = lm(desire_pres0.prop ~ value_PEV + reward_PEV + cognitive_control_PEV + craving_PEV + craving_regulation_PEV, data = model_data)
(desire_prop_mam_mods = MuMIn::dredge(desire_prop_mam_full))
```

```{r}
MuMIn::get.models(desire_prop_mam_mods, subset = TRUE) %>%
  tibble() %>%
  rename("model" = ".") %>%
  mutate(tidied = purrr::map(model, broom::tidy),
         model_num = row_number()) %>%
  select(model_num, tidied) %>%
  unnest()

best_desire_prop_mam = caret::train(desire_pres0.prop ~ value_PEV,
                     data = model_data,
                     trControl = data_ctrl,
                     method = "lm",
                     na.action = na.omit)
```

### combined
```{r}
desire_prop_null = lm(desire_pres0.prop ~ 1, data = model_data)

desire_prop_combined = caret::train(desire_pres0.prop ~ reward_ROI + value_PEV,
                     data = model_data,
                     trControl = data_ctrl,
                     method = "lm",
                     na.action = na.omit)

AIC(desire_prop_null, best_desire_prop_roi$finalModel, best_desire_prop_mam$finalModel, desire_prop_combined$finalModel) %>%
  rownames_to_column() %>%
  arrange(AIC)

```

Summarize the overall best fitting

```{r}
summary(best_desire_prop_mam$finalModel)
best_desire_prop_mam
sd(best_desire_prop_mam$resample$Rsquared)
sd(best_desire_prop_mam$resample$RMSE)
```


## enactment proportion {.tabset}
### ROI models
```{r}
enact_prop_roi_full = lm(enact_prop ~ value_ROI + reward_ROI + cognitive_control_ROI, data = model_data)
(enact_prop_roi_mods = MuMIn::dredge(enact_prop_roi_full))
```

```{r}
MuMIn::get.models(enact_prop_roi_mods, subset = TRUE) %>%
  tibble() %>%
  rename("model" = ".") %>%
  mutate(tidied = purrr::map(model, broom::tidy),
         model_num = row_number()) %>%
  select(model_num, tidied) %>%
  unnest()

best_enact_prop_roi = caret::train(enact_prop ~ reward_ROI,
                     data = model_data,
                     trControl = data_ctrl,
                     method = "lm",
                     na.action = na.omit)
```

### MAM models
```{r}
enact_prop_mam_full = lm(enact_prop ~ value_PEV + reward_PEV + cognitive_control_PEV + craving_PEV + craving_regulation_PEV, data = model_data)
(enact_prop_mam_mods = MuMIn::dredge(enact_prop_mam_full))
```

```{r}
MuMIn::get.models(enact_prop_mam_mods, subset = TRUE) %>%
  tibble() %>%
  rename("model" = ".") %>%
  mutate(tidied = purrr::map(model, broom::tidy),
         model_num = row_number()) %>%
  select(model_num, tidied) %>%
  unnest()

best_enact_prop_mam = caret::train(enact_prop ~ cognitive_control_PEV + craving_regulation_PEV + reward_PEV + value_PEV,
                     data = model_data,
                     trControl = data_ctrl,
                     method = "lm",
                     na.action = na.omit)
```

### combined
```{r}
enact_prop_null = lm(enact_prop ~ 1, data = model_data)

enact_prop_combined = caret::train(enact_prop ~ reward_ROI + cognitive_control_PEV + craving_regulation_PEV + reward_PEV + value_PEV,
                     data = model_data,
                     trControl = data_ctrl,
                     method = "lm",
                     na.action = na.omit)

AIC(enact_prop_null, best_enact_prop_roi$finalModel, best_enact_prop_mam$finalModel, enact_prop_combined$finalModel) %>%
  rownames_to_column() %>%
  arrange(AIC)

```

Summarize the overall best fitting

```{r}
summary(best_enact_prop_mam$finalModel)
best_enact_prop_mam
sd(best_enact_prop_mam$resample$Rsquared)
sd(best_enact_prop_mam$resample$RMSE)
```


